import { test, expect } from '@playwright/test';

test('laws, dangerous powers with confirmation, titan crab and measure', async ({ page }) => {
  const errs: string[] = [];
  page.on('pageerror', (e) => errs.push(e.message));
  page.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
  await page.addInitScript(() => localStorage.setItem('sotv.settings', JSON.stringify({ quality: 'high' })));
  await page.goto('/');
  await page.getByTestId('btn-new').click();
  await page.getByTestId('size-small').click();
  await page.getByTestId('btn-create').click();
  await expect(page.getByTestId('hud-stats')).toBeVisible({ timeout: 60000 });
  await page.getByTestId('btn-laws').click();
  await expect(page.getByTestId('laws-panel')).toBeVisible();
  await page.getByTestId('profile-chaos').click();
  await page.getByTestId('law-wars').click();
  await page.getByTestId('btn-laws').click();
  const box = (await page.getByTestId('world-canvas').boundingBox())!;
  const cx = box.x + box.width / 2;
  const cy = box.y + box.height / 2;
  await page.getByTestId('tab-destruction').click();
  await page.getByTestId('power-nuke').click();
  await expect(page.getByTestId('confirm')).toBeVisible();
  await page.getByTestId('confirm-yes').click();
  await page.mouse.click(cx - 60, cy);
  await page.getByTestId('power-comet').click();
  await page.getByTestId('confirm-yes').click();
  await page.mouse.click(cx + 60, cy + 40);
  await page.getByTestId('tab-creatures').click();
  await page.getByTestId('power-titancrab').click();
  await page.mouse.click(cx, cy - 40);
  await page.mouse.click(cx + 30, cy - 40);
  await page.getByTestId('tab-other').click();
  await page.getByTestId('power-measure').click();
  await page.mouse.click(cx - 20, cy - 20);
  await page.mouse.click(cx + 20, cy + 20);
  await expect(page.getByTestId('measure')).toContainText(/\d/);
  await page.getByTestId('speed-4').click();
  await page.waitForTimeout(2000);
  await page.screenshot({ path: `test-results/powers-${test.info().project.name}.png` });
  expect(errs).toEqual([]);
});
