export interface Credit {
  name: string;
  author: string;
  license: string;
  url?: string;
}

export const CREDITS: Credit[] = [
  { name: 'World graphics, tiles, creature sprites', author: 'Procedurally generated by the game code', license: 'Project license' },
  { name: 'Menu sprites (Micro Roguelike)', author: 'Kenney (kenney.nl); edits by Daniel Keenan', license: 'CC0 1.0; edits MIT', url: 'https://kenney.nl/assets/micro-roguelike' },
  { name: 'UI, impact sounds, music jingles, RPG audio', author: 'Kenney (kenney.nl)', license: 'CC0 1.0', url: 'https://kenney.nl/assets' },
  { name: 'Sound effects (100 CC0 SFX 1–2, bang, water, breaking, RPG, creature packs)', author: 'rubberduck', license: 'CC0 1.0', url: 'https://opengameart.org/content/cc0-audio-uploader-rubberduck' },
  { name: 'Music: Ambient 1–2, Theme 1', author: 'Maximiliano Stradex', license: 'CC0 1.0', url: 'https://github.com/lavenderdotpet/CC0-Public-Domain-Sounds' },
  { name: 'Music: Chronos, BeatOne, Goodnightmare, MeditatingBeat (fvi)', author: 'Team Forbidden / Warfork', license: 'CC0 1.0', url: 'https://github.com/lavenderdotpet/CC0-Public-Domain-Sounds' },
  { name: 'Generative music and fallback sounds', author: 'Synthesized at runtime with Web Audio', license: 'Project license' },
  { name: 'Preact', author: 'Jason Miller and contributors', license: 'MIT', url: 'https://preactjs.com' },
  { name: 'fflate', author: '101arrowz', license: 'MIT', url: 'https://github.com/101arrowz/fflate' },
  { name: 'Zod', author: 'Colin McDonnell', license: 'MIT', url: 'https://zod.dev' },
];
