export interface Credit {
  name: string;
  author: string;
  license: string;
  url?: string;
}

export const CREDITS: Credit[] = [
  { name: 'Graphics, tiles, sprites', author: 'Procedurally generated by the game code', license: 'Project license' },
  { name: 'Sounds and music', author: 'Synthesized at runtime with Web Audio', license: 'Project license' },
  { name: 'Preact', author: 'Jason Miller and contributors', license: 'MIT', url: 'https://preactjs.com' },
  { name: 'fflate', author: '101arrowz', license: 'MIT', url: 'https://github.com/101arrowz/fflate' },
  { name: 'Zod', author: 'Colin McDonnell', license: 'MIT', url: 'https://zod.dev' },
];
